# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    target-branch: "problemas-seguridad"

  # Enable version updates for bundler
  - package-ecosystem: "bundler"
    # Look for a `netlify-lambda` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
  
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
